// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: econ_shared_enums.proto

#include "econ_shared_enums.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr CMsgGenericResult::CMsgGenericResult(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : debug_message_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , eresult_(2u){}
struct CMsgGenericResultDefaultTypeInternal {
  constexpr CMsgGenericResultDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~CMsgGenericResultDefaultTypeInternal() {}
  union {
    CMsgGenericResult _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT CMsgGenericResultDefaultTypeInternal _CMsgGenericResult_default_instance_;
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_econ_5fshared_5fenums_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_econ_5fshared_5fenums_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_econ_5fshared_5fenums_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_econ_5fshared_5fenums_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::CMsgGenericResult, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgGenericResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::CMsgGenericResult, eresult_),
  PROTOBUF_FIELD_OFFSET(::CMsgGenericResult, debug_message_),
  1,
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::CMsgGenericResult)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_CMsgGenericResult_default_instance_),
};

const char descriptor_table_protodef_econ_5fshared_5fenums_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027econ_shared_enums.proto\">\n\021CMsgGeneric"
  "Result\022\022\n\007eresult\030\001 \001(\r:\0012\022\025\n\rdebug_mess"
  "age\030\002 \001(\t*,\n\016EGCEconBaseMsg\022\032\n\025k_EMsgGCG"
  "enericResult\020\223\024*\233\002\n\016EGCMsgResponse\022\026\n\022k_"
  "EGCMsgResponseOK\020\000\022\032\n\026k_EGCMsgResponseDe"
  "nied\020\001\022\037\n\033k_EGCMsgResponseServerError\020\002\022"
  "\033\n\027k_EGCMsgResponseTimeout\020\003\022\033\n\027k_EGCMsg"
  "ResponseInvalid\020\004\022\033\n\027k_EGCMsgResponseNoM"
  "atch\020\005\022 \n\034k_EGCMsgResponseUnknownError\020\006"
  "\022\037\n\033k_EGCMsgResponseNotLoggedOn\020\007\022\032\n\026k_E"
  "GCMsgFailedToCreate\020\010*\242\001\n\031EGCPartnerRequ"
  "estResponse\022\027\n\023k_EPartnerRequestOK\020\001\022\037\n\033"
  "k_EPartnerRequestBadAccount\020\002\022\036\n\032k_EPart"
  "nerRequestNotLinked\020\003\022+\n\'k_EPartnerReque"
  "stUnsupportedPartnerType\020\004*\305\005\n\025EGCMsgUse"
  "ItemResponse\022$\n k_EGCMsgUseItemResponse_"
  "ItemUsed\020\000\022.\n*k_EGCMsgUseItemResponse_Gi"
  "ftNoOtherPlayers\020\001\022\'\n#k_EGCMsgUseItemRes"
  "ponse_ServerError\020\002\0222\n.k_EGCMsgUseItemRe"
  "sponse_MiniGameAlreadyStarted\020\003\0221\n-k_EGC"
  "MsgUseItemResponse_ItemUsed_ItemsGranted"
  "\020\004\0227\n3k_EGCMsgUseItemResponse_DropRateBo"
  "nusAlreadyGranted\020\005\0220\n,k_EGCMsgUseItemRe"
  "sponse_NotInLowPriorityPool\020\006\022.\n*k_EGCMs"
  "gUseItemResponse_NotHighEnoughLevel\020\007\022*\n"
  "&k_EGCMsgUseItemResponse_EventNotActive\020"
  "\010\0227\n3k_EGCMsgUseItemResponse_ItemUsed_Ev"
  "entPointsGranted\020\t\022.\n*k_EGCMsgUseItemRes"
  "ponse_MissingRequirement\020\n\0220\n,k_EGCMsgUs"
  "eItemResponse_EmoticonUnlock_NoNew\020\013\0223\n/"
  "k_EGCMsgUseItemResponse_EmoticonUnlock_C"
  "omplete\020\014\022/\n+k_EGCMsgUseItemResponse_Ite"
  "mUsed_Compendium\020\rB\005H\001\200\001\000"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_econ_5fshared_5fenums_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_econ_5fshared_5fenums_2eproto = {
  false, false, 1305, descriptor_table_protodef_econ_5fshared_5fenums_2eproto, "econ_shared_enums.proto", 
  &descriptor_table_econ_5fshared_5fenums_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_econ_5fshared_5fenums_2eproto::offsets,
  file_level_metadata_econ_5fshared_5fenums_2eproto, file_level_enum_descriptors_econ_5fshared_5fenums_2eproto, file_level_service_descriptors_econ_5fshared_5fenums_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_econ_5fshared_5fenums_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_econ_5fshared_5fenums_2eproto);
  return descriptor_table_econ_5fshared_5fenums_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_econ_5fshared_5fenums_2eproto(&descriptor_table_econ_5fshared_5fenums_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCEconBaseMsg_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_econ_5fshared_5fenums_2eproto);
  return file_level_enum_descriptors_econ_5fshared_5fenums_2eproto[0];
}
bool EGCEconBaseMsg_IsValid(int value) {
  switch (value) {
    case 2579:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCMsgResponse_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_econ_5fshared_5fenums_2eproto);
  return file_level_enum_descriptors_econ_5fshared_5fenums_2eproto[1];
}
bool EGCMsgResponse_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCPartnerRequestResponse_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_econ_5fshared_5fenums_2eproto);
  return file_level_enum_descriptors_econ_5fshared_5fenums_2eproto[2];
}
bool EGCPartnerRequestResponse_IsValid(int value) {
  switch (value) {
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGCMsgUseItemResponse_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_econ_5fshared_5fenums_2eproto);
  return file_level_enum_descriptors_econ_5fshared_5fenums_2eproto[3];
}
bool EGCMsgUseItemResponse_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class CMsgGenericResult::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgGenericResult>()._has_bits_);
  static void set_has_eresult(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_debug_message(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

CMsgGenericResult::CMsgGenericResult(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMsgGenericResult)
}
CMsgGenericResult::CMsgGenericResult(const CMsgGenericResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  debug_message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_debug_message()) {
    debug_message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_debug_message(), 
      GetArena());
  }
  eresult_ = from.eresult_;
  // @@protoc_insertion_point(copy_constructor:CMsgGenericResult)
}

void CMsgGenericResult::SharedCtor() {
debug_message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
eresult_ = 2u;
}

CMsgGenericResult::~CMsgGenericResult() {
  // @@protoc_insertion_point(destructor:CMsgGenericResult)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CMsgGenericResult::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  debug_message_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void CMsgGenericResult::ArenaDtor(void* object) {
  CMsgGenericResult* _this = reinterpret_cast< CMsgGenericResult* >(object);
  (void)_this;
}
void CMsgGenericResult::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CMsgGenericResult::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CMsgGenericResult::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgGenericResult)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      debug_message_.ClearNonDefaultToEmpty();
    }
    eresult_ = 2u;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgGenericResult::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional uint32 eresult = 1 [default = 2];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_eresult(&has_bits);
          eresult_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string debug_message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_debug_message();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "CMsgGenericResult.debug_message");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CMsgGenericResult::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgGenericResult)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 eresult = 1 [default = 2];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_eresult(), target);
  }

  // optional string debug_message = 2;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_debug_message().data(), static_cast<int>(this->_internal_debug_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "CMsgGenericResult.debug_message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_debug_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgGenericResult)
  return target;
}

size_t CMsgGenericResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgGenericResult)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string debug_message = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_debug_message());
    }

    // optional uint32 eresult = 1 [default = 2];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_eresult());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CMsgGenericResult::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CMsgGenericResult)
  GOOGLE_DCHECK_NE(&from, this);
  const CMsgGenericResult* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CMsgGenericResult>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CMsgGenericResult)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CMsgGenericResult)
    MergeFrom(*source);
  }
}

void CMsgGenericResult::MergeFrom(const CMsgGenericResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CMsgGenericResult)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_debug_message(from._internal_debug_message());
    }
    if (cached_has_bits & 0x00000002u) {
      eresult_ = from.eresult_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void CMsgGenericResult::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CMsgGenericResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CMsgGenericResult::CopyFrom(const CMsgGenericResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgGenericResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgGenericResult::IsInitialized() const {
  return true;
}

void CMsgGenericResult::InternalSwap(CMsgGenericResult* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  debug_message_.Swap(&other->debug_message_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(eresult_, other->eresult_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgGenericResult::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CMsgGenericResult* Arena::CreateMaybeMessage< ::CMsgGenericResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgGenericResult >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
